# fly.toml app configuration file generated for botzic on 2023-07-06T01:08:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "botzic"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  TZ="America/Guatemala"
